-- ============================================================================
-- SatCity Hospital — Full Production Database Seeding Script
--
-- This script populates both auth.users (Supabase Authentication) and
-- public schemas so you can log in with password "password123" for
-- any of the pre-seeded users.
--
-- Run this in your Supabase SQL Editor (supabase.com → SQL Editor)
-- after running schema.sql and auth-trigger.sql.
-- ============================================================================

-- Blowfish crypt hash for "password123"
-- '$2a$10$fV27v4C4G03Y8.z7B8I0iOaN9eF7Vun79mYm541z0r9.Fv.Xy2IqK'

-- 1. Insert Departments first
insert into public.departments (id, name, admin_id)
values
  ('d-cardio', 'Cardiology', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a22'),
  ('d-neuro', 'Neurology', null),
  ('d-peds', 'Pediatrics', null),
  ('d-ortho', 'Orthopedics', null)
on conflict (id) do update set name = excluded.name;

-- 2. Insert into auth.users (Supabase internal table)
-- This will automatically trigger handle_new_user() to create entries in public.users, public.doctors, and public.patients.
insert into auth.users (
  id,
  instance_id,
  email,
  encrypted_password,
  email_confirmed_at,
  raw_app_meta_data,
  raw_user_meta_data,
  created_at,
  updated_at,
  role,
  aud,
  confirmation_token
)
values
  -- Super Admin
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', '00000000-0000-0000-0000-000000000000', 'super@satcity.com', crypt('password123', gen_salt('bf', 10)), now(), '{"provider":"email","providers":["email"]}'::jsonb, '{"full_name":"Dr. Adaeze Okafor","role":"super_admin"}'::jsonb, now(), now(), 'authenticated', 'authenticated', ''),

  -- Cardiology Admin
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a22', '00000000-0000-0000-0000-000000000000', 'admin.cardio@satcity.com', crypt('password123', gen_salt('bf', 10)), now(), '{"provider":"email","providers":["email"]}'::jsonb, '{"full_name":"Chidi Nwosu","role":"admin"}'::jsonb, now(), now(), 'authenticated', 'authenticated', ''),

  -- Doctor: Dr. Emeka Uzoma
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a33', '00000000-0000-0000-0000-000000000000', 'emeka@satcity.com', crypt('password123', gen_salt('bf', 10)), now(), '{"provider":"email","providers":["email"]}'::jsonb, '{"full_name":"Dr. Emeka Uzoma","role":"doctor","specialty":"Cardiology,Hypertension","bio":"Consultant cardiologist with 12 years of experience."}'::jsonb, now(), now(), 'authenticated', 'authenticated', ''),

  -- Lab Technician: Kemi Adegoke
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a44', '00000000-0000-0000-0000-000000000000', 'kemi@satcity.com', crypt('password123', gen_salt('bf', 10)), now(), '{"provider":"email","providers":["email"]}'::jsonb, '{"full_name":"Kemi Adegoke","role":"lab_tech"}'::jsonb, now(), now(), 'authenticated', 'authenticated', ''),

  -- Pharmacist: Bola Adeyemi
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a55', '00000000-0000-0000-0000-000000000000', 'bola@satcity.com', crypt('password123', gen_salt('bf', 10)), now(), '{"provider":"email","providers":["email"]}'::jsonb, '{"full_name":"Bola Adeyemi","role":"pharmacist"}'::jsonb, now(), now(), 'authenticated', 'authenticated', ''),

  -- Patient: Chioma Nwachukwu
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a66', '00000000-0000-0000-0000-000000000000', 'chioma@example.com', crypt('password123', gen_salt('bf', 10)), now(), '{"provider":"email","providers":["email"]}'::jsonb, '{"full_name":"Chioma Nwachukwu","role":"patient","blood_type":"O+","date_of_birth":"1992-06-14","emergency_contact":"+234 801 223 1190","address":"14 Lekki Phase 1, Lagos"}'::jsonb, now(), now(), 'authenticated', 'authenticated', '')
on conflict (id) do nothing;

-- 3. Update department bindings and activation statuses for staff
update public.users set department_id = 'd-cardio', is_active = true where id = 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a22'; -- Admin
update public.users set department_id = 'd-cardio', is_active = true where id = 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a33'; -- Doctor
update public.users set department_id = 'd-cardio', is_active = true where id = 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a44'; -- Lab tech
update public.users set is_active = true where id = 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a55'; -- Pharmacist

-- Update doctor profile to available so they are ready for assignments
update public.doctors set availability_status = 'available', active_patient_count = 1 where user_id = 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a33';

-- 4. Get the patient_id and doctor_id generated by the triggers
-- We use a PL/pgSQL block or subqueries to map them accurately
do $$
declare
  v_patient_id uuid;
  v_doctor_id uuid;
begin
  select id into v_patient_id from public.patients where user_id = 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a66';
  select id into v_doctor_id from public.doctors where user_id = 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a33';

  -- 5. Seed Patient Symptoms
  update public.patients
  set symptoms = '[
    {
      "id": "s1",
      "text": "Recurring chest tightness, shortness of breath after light exercise, occasional dizziness.",
      "at": "2026-03-01T10:00:00.000Z",
      "lab_test_ordered": "ECG + Lipid Panel",
      "lab_test_status": "Results Uploaded"
    }
  ]'::jsonb
  where id = v_patient_id;

  -- 6. Seed Lab Results
  insert into public.lab_results (id, patient_id, technician_id, diagnosed_condition, result_file_url, uploaded_at)
  values (
    'e0eebc99-9c0b-4ef8-bb6d-6bb9bd380f11',
    v_patient_id,
    'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a44',
    'Hypertension',
    'result_chioma_ecg.pdf',
    now() - interval '3 days'
  ) on conflict (id) do nothing;

  -- 7. Seed Patient-Doctor Assignment
  insert into public.patient_doctor_assignments (id, patient_id, doctor_id, assigned_at, status)
  values (
    'e0eebc99-9c0b-4ef8-bb6d-6bb9bd380f22',
    v_patient_id,
    v_doctor_id,
    now() - interval '3 days',
    'active'
  ) on conflict (id) do nothing;

  -- 8. Seed Treatments
  insert into public.treatments (id, patient_id, doctor_id, illness_type, treatment_details, basis_type, administered_at)
  values (
    'e0eebc99-9c0b-4ef8-bb6d-6bb9bd380f33',
    v_patient_id,
    'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a33', -- Dr. Emeka User ID
    'Hypertension Stage 1',
    'Prescribed Amlodipine 5mg daily. Lifestyle counseling, low-sodium diet plan. Follow-up in 2 weeks.',
    'lab_confirmed',
    now() - interval '2 days'
  ) on conflict (id) do nothing;

  -- 9. Seed Ambulance Bookings
  insert into public.ambulance_bookings (id, patient_id, patient_name, type, pickup_location, destination, scheduled_time, reason, status)
  values (
    'e0eebc99-9c0b-4ef8-bb6d-6bb9bd380f44',
    'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a66', -- Chioma User ID
    'Chioma Nwachukwu',
    'scheduled',
    '14 Lekki Phase 1, Lagos',
    'SatCity Hospital, Victoria Island',
    now() + interval '3 days',
    'Follow-up appointment with cardiology',
    'Confirmed'
  ) on conflict (id) do nothing;
end $$;

-- 10. Seed Drug Inventory
insert into public.drug_inventory (id, sanity_drug_id, drug_name, category, description, usage, side_effects, quantity, status, updated_at)
values
  ('d0eebc99-9c0b-4ef8-bb6d-6bb9bd380d11', 's-dr-1', 'Amlodipine 5mg', 'Cardiovascular', 'Calcium channel blocker for hypertension.', 'One tablet orally once daily.', 'Ankle edema, flushing, headache.', 240, 'available', now()),
  ('d0eebc99-9c0b-4ef8-bb6d-6bb9bd380d22', 's-dr-2', 'Artemether-Lumefantrine 20/120mg', 'Antimalarial', 'First-line ACT for uncomplicated malaria.', '6-dose regimen over 3 days with fatty meal.', 'Nausea, dizziness, headache.', 8, 'low', now()),
  ('d0eebc99-9c0b-4ef8-bb6d-6bb9bd380d33', 's-dr-3', 'Sumatriptan 50mg', 'Neurology', 'Serotonin agonist for acute migraine attacks.', 'One tablet at onset; may repeat after 2 hours.', 'Tingling, chest tightness, dizziness.', 0, 'out_of_stock', now()),
  ('d0eebc99-9c0b-4ef8-bb6d-6bb9bd380d44', 's-dr-4', 'Paracetamol 500mg', 'Analgesic', 'Non-opioid analgesic and antipyretic.', '1-2 tablets every 4-6 hours, max 8/day.', 'Rare, liver toxicity at overdose.', 1200, 'available', now()),
  ('d0eebc99-9c0b-4ef8-bb6d-6bb9bd380d55', 's-dr-5', 'Metformin 500mg', 'Endocrine', 'First-line therapy for Type 2 diabetes.', 'One tablet twice daily with meals.', 'GI upset, lactic acidosis (rare).', 480, 'available', now()),
  ('d0eebc99-9c0b-4ef8-bb6d-6bb9bd380d66', 's-dr-6', 'Ibuprofen 400mg', 'Analgesic', 'NSAID for pain and inflammation.', 'One tablet every 6-8 hours with food.', 'Gastric irritation, renal effects.', 6, 'low', now())
on conflict (sanity_drug_id) do update set
  quantity = excluded.quantity,
  status = excluded.status;

-- 11. Print verification of seeded profiles
select id, email, role, is_active from public.users;
